stages:
  - test
  - post-test

before_script:
  - date

after_script:
  - date


# For package caching
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

.junit_test_results: &junit_test_results
  artifacts:
    reports:
      junit: .pytest-junit.xml
    expire_in: 4 weeks


# Create the core definition of the test; TOXENV and image defined in each main job.
.core_test_definition: &core_test_definition
  stage: test
  cache:
    key: "python3"
    paths:
      - .cache/
  script:
    # Build out the docker image with what we need to get the tests rolling
    - apk add --update libffi-dev python3 python3-dev make g++ git
    - python3 -V
    - wget -O - https://bootstrap.pypa.io/get-pip.py | python3
    - pip install pipenv
    # Start the test stuff.
    - make tox


python35:
  <<: *core_test_definition
  image: python:3.5-alpine
  variables:
    TOXENV: "py35"

python36:
  <<: *core_test_definition
  image: python:3.6-alpine
  variables:
    TOXENV: "py36"

python37:
  <<: *core_test_definition
  image: python:3.7-alpine
  variables:
    TOXENV: "py37"

python38:
  <<: *core_test_definition
  image: python:3.8-alpine
  variables:
    TOXENV: "py38"


# SAST/Code Quality -- GitLab templates, with overrides for artifacts
include:
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

sast:
  stage: post-test
  artifacts:
    expire_in: 2 weeks

code_quality:
  stage: post-test
  artifacts:
    expire_in: 2 weeks
